/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'MarkPerry' at '26/06/14 7:49 PM' with Gradle 1.12
 *
 * @author MarkPerry, @date 26/06/14 7:49 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
